apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-api
  labels:
    app: taskflow-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: taskflow-api
  template:
    metadata:
      labels:
        app: taskflow-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: taskflow-config
          env:
            # Read password from Secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskflow-secret
                  key: dbPassword
            # Construct the connection string using Kubernetes native variable interpolation $(...)
            - name: DATABASE_URL
              value: "postgresql+psycopg2://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
          ports:
            - containerPort: {{ .Values.api.containerPort }}
