apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secret
  labels:
    app: taskflow
type: Opaque
stringData:
  # stringData in Helm is useful. Kubernetes will do base64 encrypt for you
  dbPassword: {{ .Values.secret.dbPassword | quote }}
  jwtSecret: {{ .Values.secret.jwtSecret | quote }}
