apiVersion: v1
kind: Service
metadata:
  name: taskflow-web
  labels:
    app: taskflow-web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: taskflow-web
