apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-postgres
  namespace: taskflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-postgres
  template:
    metadata:
      labels:
        app: taskflow-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: taskflow
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: taskflow-postgres
  namespace: taskflow
spec:
  selector:
    app: taskflow-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
