namespace: taskflow

imagePullSecrets: []

api:
  replicaCount: 1
  image:
    repository: 485104726319.dkr.ecr.ca-central-1.amazonaws.com/taskflow/api
    tag: v1.0.1
    pullPolicy: IfNotPresent
  containerPort: 8000
  service:
    port: 8000

web:
  replicaCount: 1
  image:
    repository: 692735150780.dkr.ecr.us-east-1.amazonaws.com/taskflow/web
    tag: v1.0.6
    pullPolicy: IfNotPresent
  containerPort: 3000
  service:
    port: 3000

postgres:
  enabled: true
  image: postgres:16-alpine
  port: 5432
  storage: 1Gi

config:
  dbHost: taskflow-postgres
  dbPort: "5432"
  dbName: taskflow
  dbUser: postgres

secret:
  # Override these sensitive values in values-local.yaml for local dev or production!
  dbPassword: "change-me-in-production"
  jwtSecret: "change-me-in-production"

ingress:
  enabled: false
  className: ""
  host: taskflow.local
  path: /
  pathType: Prefix